### PR TITLE
Remove chat integration

### PR DESCRIPTION
**Pull request by ddgenome**
Remove optional chat integration and sending of chat messages for
publish step.

### CODE REVIEW

**Comment by cdupuis** [comment]
What do you think about removing the resource provider dependency but leaving the actual slack message sending in? Those don't hurt and will only really be delivered when a chat team is linked.

**Comment by ddgenome** [comment]
I did not know that was an option. So the `ctx.message` is available regardless of whether the skill declares a chat resource provider?

It's fine with me to keep the Slack messages in, although personally as long as the commit check is rendered, I'm good.

**Comment by cdupuis** [comment]
Yes, for chat it is an option.

**Review by cdupuis — APPROVED** [review]

**Comment by ddgenome** [comment]
Did you want me to restore those chat messages?

**Pull request merged**
